color:
    path:     /
    defaults: { _controller: "AppBundle:Color:index" }

color_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Color:show" }

color_new:
    path:     /new
    defaults: { _controller: "AppBundle:Color:new" }

color_create:
    path:     /create
    defaults: { _controller: "AppBundle:Color:create" }
    methods:  POST

color_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Color:edit" }

color_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Color:update" }
    methods:  [POST, PUT]

color_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Color:delete" }
    methods:  [POST, DELETE]
