size:
    path:     /
    defaults: { _controller: "AppBundle:Size:index" }

size_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Size:show" }

size_new:
    path:     /new
    defaults: { _controller: "AppBundle:Size:new" }

size_create:
    path:     /create
    defaults: { _controller: "AppBundle:Size:create" }
    methods:  POST

size_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Size:edit" }

size_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Size:update" }
    methods:  [POST, PUT]

size_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Size:delete" }
    methods:  [POST, DELETE]
