sub_category:
    path:     /
    defaults: { _controller: "AppBundle:Sub_category:index" }

sub_category_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:Sub_category:show" }

sub_category_new:
    path:     /new
    defaults: { _controller: "AppBundle:Sub_category:new" }

sub_category_create:
    path:     /create
    defaults: { _controller: "AppBundle:Sub_category:create" }
    methods:  POST

sub_category_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:Sub_category:edit" }

sub_category_update:
    path:     /{id}/update
    defaults: { _controller: "AppBundle:Sub_category:update" }
    methods:  [POST, PUT]

sub_category_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:Sub_category:delete" }
    methods:  [POST, DELETE]
