AppBundle\Entity\Sub_category:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\Sub_categoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '50'
    lifecycleCallbacks: {  }
