<?php

namespace AppBundle\Entity;

/**
 * ComandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComandRepository extends \Doctrine\ORM\EntityRepository
{
}
